=head1 Installing Act on your system


This doc is being rewritten. Here's the new outline:

    install pre-requesites
      postgresql 8.x apache 1.x mod_perl 1.x
      cpan modules
    create databases
    download act
      svn co
    configure act
      PERL5LIB / ACTHOME
      create sample conference
        mkdir actdocs;
        cp -pr skel/
        cp -pr skel/actdocs actdocs/sample
      configure act
        cp -pr eg/conf .
        configure act.ini
          database
    make test
    configure apache
       vhost stuff
    test
       http://localhost/sample/


NOTES on compiling Apache 1.3 on Ubuntu

Use :
    bash ./configure --prefix=/usr/local/httpd --enable-shared=max  --enable-module=rewrite --enable-module=expires

Because under Ubuntu, sh is a symlink to dash, which breaks configure.

 make && make install

compiling mod_perl

perl Makefile.PL USE_APXS=1 WITH_APXS=/usr/local/httpd/bin/apxs EVERYTHING=1


Install (or svn checkout) Act in a directory. In this document we'll
use /home/act, and refer to it as Act's home directory.

The required modules are tested for in t/01cpan.t. You'll find the
complete and up-to-date list of prerequisites in that file.

First thing is to enable Perl (and mod_perl) to find the Act modules.

    export PERL5LIB=/home/act/lib

Act needs to know its home directory so that it can find its
configuration file. This is done by setting the ACTHOME environment variable:

    export ACTHOME=/home/act

Make sure both ACTHOME and PERL5LIB are set and exported when
running httpd or 'make test': include these settings in both your
shell profile (~/.bashrc or equivalent) and Apache startup script
(apachectl or equivalent.)

Next, define a virtual host in your Apache configuration file
(httpd.conf) for Act. Here's an example:

    <VirtualHost *>
      ServerName   localhost
      ServerAdmin  webmaster@example.com
      DocumentRoot /home/act/wwwdocs
      Include      /home/act/conf/httpd.conf
    </VirtualHost>

For code development it is useful to install the C<Apache::Reload>
module. Enable it in httpd.conf (outside of any VirtualHost
containers):

    PerlModule Apache::Reload
    PerlInitHandler Apache::Reload
    PerlSetVar ReloadAll Off

Then add this inside Act's VirtualHost container:

    PerlSetVar ReloadModules "Act::*"

If you don't want to mess with name-based virtual hosts and DNS,
an easy setup is to use a port-based virtual host:

    Listen 9000
    <VirtualHost *:9000>
      Port 9000
      ServerName   localhost
      ServerAdmin  webmaster@example.com
      DocumentRoot /home/act/wwwdocs
      Include      /home/act/conf/httpd.conf
    </VirtualHost>

Create the directory where photos will be uploaded, by default
F<$ACTHOME/wwwdocs/photos>. Make sure it is readable by all, and
writable by the user running Apache.

Now edit C<conf/act.ini> and enter your settings

    [database]
    name        = act
    dsn         = dbi:Pg:dbname=$(database_name)
    user        = foo
    passwd      = sekr3t
    
    [general]
    conferences = act-2004
    

To make sure that your system has all the requirements to run Act,
and that Act works correctly on it, you can now run Act's test suite.
This test suite requires Test::More.

    cd $ACTHOME
    make test

=head1 Adding a new conference

Decide the name of your conference. We'll use act-2004 as an example.

  $ACTHOME/
      actdocs/
        act-2004/
          conf/             # local configuration
          static/           # "static" multilingual .html pages
          templates/        # local templates or global overrides
      wwwdocs/              # static files
          photos/           # user photos (general_dir_photos conf item)
          act-2004/
              css/
              images/

=cut

