=head1 NAME

Act::Manual::Provider::Payment - The Act online payment architecture

=head1 DESCRIPTION

This document describes the architecture of Act's online payment subsystem.
This system defers the actual purchasing to a third party, usually a bank.
We allow for pluggable backends to target various online payment solutions.

Currently implemented backends are YEF, used by the YAPC::Europe Foundation,
and TPF, used by The Perl Foundation. Online payment funds end up in the
selected foundation's bank account. The foundation then forwards them back to the
organizers. Using either backend requires prior agreement between the organizers
and the relevant foundation.

YEF currently accepts payments in euros. TPF currently accepts payments in
US dollars.

There's also a Fake backend which simulates a purchase for testing purposes.

The system is configured from each conference's C<conf/act.ini> configuration
file.

  [payment]
  open        = 1
  type        = YEF

Set C<open> to 1 to enable, or to 0 to disable, the online payment system.
C<type> should be set to the appropriate backend: C<YEF>, C<TPF> or C<Fake>.

Let's now walk through the steps involved in a purchase.

=over 4

=item *

In her main page, a user is invited to purchase a ticket to the conference
if she's registered and hasn't yet paid.

=item *

Clicking the C<purchase> button invokes C<Act::Handler::User::Purchase>.
This fetches the prices from the database table and displays the
purchase form via F<templates/user/purchase>. This template can be overriden
and customized on a per-conference basis.

=item *

When a purchase form with a valid price is submitted,  C<Act::Handler::User::Purchase>
creates a new order in the database with a status of C<init>.

We then call the plugged backend (C<Act::Payment::Foo>) to create a form
which contains encrypted information about the purchase order. When this form
is submitted, the user is taken to the bank's web site.

=item *

The bank handles credit card input and validation, and offers a link back
to the user's main page in the conference.

=item *

Meanwhile, the bank sends us an HTTP request with the status of the purchase.

=back

=cut

=head1 AUTHOR

Éric Cholet

=head1 COPYRIGHT

Copyright (C) 2004-2007, by Philippe Bruhat and Éric Cholet.
All Rights Reserved.

This module is free software; you can redistribute it and/or
modify it under the same terms as Perl itself.

=cut

