=head1 Act performance hints

This section needs to be rewritten: We do not have experience how the
PSGI based implementations perform.

The PSGI implementation comes as a persistent Perl interpreter out of
the box, so the "old" mod_perl mechanism of preloading modules is no
longer required.

A quite popular setup is to run Nginx as a frontend and L<starman> as
the PSGI backend for Act.
