=head1 News

=head2 Including news in a static page

  [% PROCESS common %]
  <div class="newsbox">
    [% FOREACH item = news %]
    <p><h3>[% item.title %]</h3>
    <em>[% date_format(item.datetime, 'datetime_short') %] by [% user_info(item.user) %]</em>
    <br>
    [% item.content %]</p>
    [% END %]
  </div>

The number of items can be limited by supplying a count argument to C<news>:

  [% FOREACH item = news(5) %]

=head2 Atom feed

News items are available as an Atom feed. The feed's URL is

  /conf_id/news.xml

You can make this feed available by including the following line in the
E<lt>headE<gt> section of your pages, for example in your C<ui> template:

  <link rel="alternate" type="application/atom+xml" title="My Atom Feed" href="http://domain/conf_id/news.xml" />

Replace C<domain> with your site's domain name, and C<conf_id> with your conference name.

If you're creating news feeds in several languages, specify the language as a query string:

  <link rel="alternate" type="application/atom+xml" title="[% global.conference.name %]"
      href="[% global.request.base_url %][% make_uri( 'news.xml', 'language', global.request.language ) %]" />
