/** ENGLISH */
/* civility */
INSERT INTO translations VALUES('users', 'civility', 1, 'en', 'Mr.');
INSERT INTO translations VALUES('users', 'civility', 2, 'en', 'Mrs.');
INSERT INTO translations VALUES('users', 'civility', 3, 'en', 'Ms.');

/* hard coded rooms */
INSERT INTO translations VALUES ('rooms', 'name', 'out', 'en', 'Outside' );
INSERT INTO translations VALUES ('rooms', 'name', 'venue', 'en', 'Venue' );

/* payment means */
INSERT INTO translations VALUES ('payment', 'name', 'CHQ',    'en', 'Cheque' );
INSERT INTO translations VALUES ('payment', 'name', 'CASH',   'en', 'Cash' );
INSERT INTO translations VALUES ('payment', 'name', 'ONLINE', 'en', 'Online' );

/* ISO-3166 country codes (http://www.ics.uci.edu/pub/websoft/wwwstat/country-codes.txt) */
INSERT INTO translations VALUES ('countries', 'iso', 'ad', 'en', 'Andorra');
INSERT INTO translations VALUES ('countries', 'iso', 'ae', 'en', 'United Arab Emirates');
INSERT INTO translations VALUES ('countries', 'iso', 'af', 'en', 'Afghanistan');
INSERT INTO translations VALUES ('countries', 'iso', 'ag', 'en', 'Antigua and Barbuda');
INSERT INTO translations VALUES ('countries', 'iso', 'ai', 'en', 'Anguilla');
INSERT INTO translations VALUES ('countries', 'iso', 'al', 'en', 'Albania');
INSERT INTO translations VALUES ('countries', 'iso', 'am', 'en', 'Armenia');
INSERT INTO translations VALUES ('countries', 'iso', 'an', 'en', 'Netherlands Antilles');
INSERT INTO translations VALUES ('countries', 'iso', 'ao', 'en', 'Angola');
INSERT INTO translations VALUES ('countries', 'iso', 'ar', 'en', 'Argentina');
INSERT INTO translations VALUES ('countries', 'iso', 'at', 'en', 'Austria');
INSERT INTO translations VALUES ('countries', 'iso', 'au', 'en', 'Australia');
INSERT INTO translations VALUES ('countries', 'iso', 'aw', 'en', 'Aruba');
INSERT INTO translations VALUES ('countries', 'iso', 'az', 'en', 'Azerbaijan');
INSERT INTO translations VALUES ('countries', 'iso', 'ba', 'en', 'Bosnia and Herzegovina');
INSERT INTO translations VALUES ('countries', 'iso', 'bb', 'en', 'Barbados');
INSERT INTO translations VALUES ('countries', 'iso', 'bd', 'en', 'Bangladesh');
INSERT INTO translations VALUES ('countries', 'iso', 'be', 'en', 'Belgium');
INSERT INTO translations VALUES ('countries', 'iso', 'bf', 'en', 'Burkina Faso');
INSERT INTO translations VALUES ('countries', 'iso', 'bg', 'en', 'Bulgaria');
INSERT INTO translations VALUES ('countries', 'iso', 'bh', 'en', 'Bahrain');
INSERT INTO translations VALUES ('countries', 'iso', 'bi', 'en', 'Burundi');
INSERT INTO translations VALUES ('countries', 'iso', 'bj', 'en', 'Benin');
INSERT INTO translations VALUES ('countries', 'iso', 'bm', 'en', 'Bermuda');
INSERT INTO translations VALUES ('countries', 'iso', 'bn', 'en', 'Brunei Darussalam');
INSERT INTO translations VALUES ('countries', 'iso', 'bo', 'en', 'Bolivia');
INSERT INTO translations VALUES ('countries', 'iso', 'br', 'en', 'Brazil');
INSERT INTO translations VALUES ('countries', 'iso', 'bs', 'en', 'Bahamas');
INSERT INTO translations VALUES ('countries', 'iso', 'bt', 'en', 'Bhutan');
INSERT INTO translations VALUES ('countries', 'iso', 'bw', 'en', 'Botswana');
INSERT INTO translations VALUES ('countries', 'iso', 'by', 'en', 'Belarus');
INSERT INTO translations VALUES ('countries', 'iso', 'bz', 'en', 'Belize');
INSERT INTO translations VALUES ('countries', 'iso', 'ca', 'en', 'Canada');
INSERT INTO translations VALUES ('countries', 'iso', 'cf', 'en', 'Central African Republic');
INSERT INTO translations VALUES ('countries', 'iso', 'cg', 'en', 'Congo');
INSERT INTO translations VALUES ('countries', 'iso', 'ch', 'en', 'Switzerland');
INSERT INTO translations VALUES ('countries', 'iso', 'ci', 'en', 'Côte d\'Ivoire');
INSERT INTO translations VALUES ('countries', 'iso', 'cl', 'en', 'Chile');
INSERT INTO translations VALUES ('countries', 'iso', 'cm', 'en', 'Cameroon');
INSERT INTO translations VALUES ('countries', 'iso', 'cn', 'en', 'China');
INSERT INTO translations VALUES ('countries', 'iso', 'co', 'en', 'Colombia');
INSERT INTO translations VALUES ('countries', 'iso', 'cr', 'en', 'Costa Rica');
INSERT INTO translations VALUES ('countries', 'iso', 'cu', 'en', 'Cuba');
INSERT INTO translations VALUES ('countries', 'iso', 'cv', 'en', 'Cape Verde');
INSERT INTO translations VALUES ('countries', 'iso', 'cx', 'en', 'Christmas Island');
INSERT INTO translations VALUES ('countries', 'iso', 'cy', 'en', 'Cyprus');
INSERT INTO translations VALUES ('countries', 'iso', 'cz', 'en', 'Czech Republic');
INSERT INTO translations VALUES ('countries', 'iso', 'de', 'en', 'Germany');
INSERT INTO translations VALUES ('countries', 'iso', 'dj', 'en', 'Djibouti');
INSERT INTO translations VALUES ('countries', 'iso', 'dk', 'en', 'Denmark');
INSERT INTO translations VALUES ('countries', 'iso', 'dm', 'en', 'Dominica');
INSERT INTO translations VALUES ('countries', 'iso', 'do', 'en', 'Dominican Republic');
INSERT INTO translations VALUES ('countries', 'iso', 'dz', 'en', 'Algeria');
INSERT INTO translations VALUES ('countries', 'iso', 'ec', 'en', 'Ecuador');
INSERT INTO translations VALUES ('countries', 'iso', 'ee', 'en', 'Estonia');
INSERT INTO translations VALUES ('countries', 'iso', 'eg', 'en', 'Egypt');
INSERT INTO translations VALUES ('countries', 'iso', 'eh', 'en', 'Western Sahara');
INSERT INTO translations VALUES ('countries', 'iso', 'er', 'en', 'Eritrea');
INSERT INTO translations VALUES ('countries', 'iso', 'es', 'en', 'Spain');
INSERT INTO translations VALUES ('countries', 'iso', 'et', 'en', 'Ethiopia');
INSERT INTO translations VALUES ('countries', 'iso', 'fi', 'en', 'Finland');
INSERT INTO translations VALUES ('countries', 'iso', 'fj', 'en', 'Fiji');
INSERT INTO translations VALUES ('countries', 'iso', 'fr', 'en', 'France');
INSERT INTO translations VALUES ('countries', 'iso', 'ga', 'en', 'Gabon');
INSERT INTO translations VALUES ('countries', 'iso', 'gd', 'en', 'Grenada');
INSERT INTO translations VALUES ('countries', 'iso', 'ge', 'en', 'Georgia');
INSERT INTO translations VALUES ('countries', 'iso', 'gh', 'en', 'Ghana');
INSERT INTO translations VALUES ('countries', 'iso', 'gi', 'en', 'Gibraltar');
INSERT INTO translations VALUES ('countries', 'iso', 'gl', 'en', 'Gambia');
INSERT INTO translations VALUES ('countries', 'iso', 'gn', 'en', 'Guinea');
INSERT INTO translations VALUES ('countries', 'iso', 'gq', 'en', 'Equatorial Guinea');
INSERT INTO translations VALUES ('countries', 'iso', 'gr', 'en', 'Greece');
INSERT INTO translations VALUES ('countries', 'iso', 'gt', 'en', 'Guatemala');
INSERT INTO translations VALUES ('countries', 'iso', 'gw', 'en', 'Guinea-Bissau');
INSERT INTO translations VALUES ('countries', 'iso', 'gy', 'en', 'Guyana');
INSERT INTO translations VALUES ('countries', 'iso', 'hk', 'en', 'Hong Kong');
INSERT INTO translations VALUES ('countries', 'iso', 'hn', 'en', 'Honduras');
INSERT INTO translations VALUES ('countries', 'iso', 'hr', 'en', 'Croatia');
INSERT INTO translations VALUES ('countries', 'iso', 'ht', 'en', 'Haiti');
INSERT INTO translations VALUES ('countries', 'iso', 'hu', 'en', 'Hungary');
INSERT INTO translations VALUES ('countries', 'iso', 'id', 'en', 'Indonesia');
INSERT INTO translations VALUES ('countries', 'iso', 'ie', 'en', 'Ireland');
INSERT INTO translations VALUES ('countries', 'iso', 'il', 'en', 'Israel');
INSERT INTO translations VALUES ('countries', 'iso', 'in', 'en', 'India');
INSERT INTO translations VALUES ('countries', 'iso', 'iq', 'en', 'Iraq');
INSERT INTO translations VALUES ('countries', 'iso', 'ir', 'en', 'Iran');
INSERT INTO translations VALUES ('countries', 'iso', 'is', 'en', 'Iceland');
INSERT INTO translations VALUES ('countries', 'iso', 'it', 'en', 'Italy');
INSERT INTO translations VALUES ('countries', 'iso', 'jm', 'en', 'Jamaica');
INSERT INTO translations VALUES ('countries', 'iso', 'jo', 'en', 'Jordan');
INSERT INTO translations VALUES ('countries', 'iso', 'jp', 'en', 'Japan');
INSERT INTO translations VALUES ('countries', 'iso', 'ke', 'en', 'Kenya');
INSERT INTO translations VALUES ('countries', 'iso', 'kg', 'en', 'Kyrgyzstan');
INSERT INTO translations VALUES ('countries', 'iso', 'ki', 'en', 'Kiribati');
INSERT INTO translations VALUES ('countries', 'iso', 'kh', 'en', 'Cambodia');
INSERT INTO translations VALUES ('countries', 'iso', 'km', 'en', 'Comoros');
INSERT INTO translations VALUES ('countries', 'iso', 'kn', 'en', 'Saint Kitts and Nevis');
INSERT INTO translations VALUES ('countries', 'iso', 'kp', 'en', 'Korea, North');
INSERT INTO translations VALUES ('countries', 'iso', 'kr', 'en', 'Korea, South');
INSERT INTO translations VALUES ('countries', 'iso', 'kw', 'en', 'Kuwait');
INSERT INTO translations VALUES ('countries', 'iso', 'ky', 'en', 'Cayman Islands');
INSERT INTO translations VALUES ('countries', 'iso', 'kz', 'en', 'Kazakhstan');
INSERT INTO translations VALUES ('countries', 'iso', 'la', 'en', 'Laos');
INSERT INTO translations VALUES ('countries', 'iso', 'lb', 'en', 'Lebanon');
INSERT INTO translations VALUES ('countries', 'iso', 'lc', 'en', 'Saint Lucia');
INSERT INTO translations VALUES ('countries', 'iso', 'li', 'en', 'Liechtenstein');
INSERT INTO translations VALUES ('countries', 'iso', 'lk', 'en', 'Sri Lanka');
INSERT INTO translations VALUES ('countries', 'iso', 'lr', 'en', 'Liberia');
INSERT INTO translations VALUES ('countries', 'iso', 'ls', 'en', 'Lesotho');
INSERT INTO translations VALUES ('countries', 'iso', 'lt', 'en', 'Lithuania');
INSERT INTO translations VALUES ('countries', 'iso', 'lu', 'en', 'Luxembourg');
INSERT INTO translations VALUES ('countries', 'iso', 'lv', 'en', 'Latvia');
INSERT INTO translations VALUES ('countries', 'iso', 'ly', 'en', 'Libya');
INSERT INTO translations VALUES ('countries', 'iso', 'ma', 'en', 'Morocco');
INSERT INTO translations VALUES ('countries', 'iso', 'mc', 'en', 'Monaco');
INSERT INTO translations VALUES ('countries', 'iso', 'md', 'en', 'Moldova');
INSERT INTO translations VALUES ('countries', 'iso', 'mg', 'en', 'Madagascar');
INSERT INTO translations VALUES ('countries', 'iso', 'mk', 'en', 'Macedonia');
INSERT INTO translations VALUES ('countries', 'iso', 'mh', 'en', 'Marshall Islands');
INSERT INTO translations VALUES ('countries', 'iso', 'ml', 'en', 'Mali');
INSERT INTO translations VALUES ('countries', 'iso', 'mm', 'en', 'Myanmar');
INSERT INTO translations VALUES ('countries', 'iso', 'mn', 'en', 'Mongolia');
INSERT INTO translations VALUES ('countries', 'iso', 'mo', 'en', 'Macao');
INSERT INTO translations VALUES ('countries', 'iso', 'mr', 'en', 'Mauritania');
INSERT INTO translations VALUES ('countries', 'iso', 'ms', 'en', 'Montserrat');
INSERT INTO translations VALUES ('countries', 'iso', 'mt', 'en', 'Malta');
INSERT INTO translations VALUES ('countries', 'iso', 'mu', 'en', 'Mauritius');
INSERT INTO translations VALUES ('countries', 'iso', 'mv', 'en', 'Maldives');
INSERT INTO translations VALUES ('countries', 'iso', 'mw', 'en', 'Malawi');
INSERT INTO translations VALUES ('countries', 'iso', 'mx', 'en', 'Mexico');
INSERT INTO translations VALUES ('countries', 'iso', 'my', 'en', 'Malaysia');
INSERT INTO translations VALUES ('countries', 'iso', 'mz', 'en', 'Mozambique');
INSERT INTO translations VALUES ('countries', 'iso', 'na', 'en', 'Namibia');
INSERT INTO translations VALUES ('countries', 'iso', 'ne', 'en', 'Niger');
INSERT INTO translations VALUES ('countries', 'iso', 'ng', 'en', 'Nigeria');
INSERT INTO translations VALUES ('countries', 'iso', 'ni', 'en', 'Nicaragua');
INSERT INTO translations VALUES ('countries', 'iso', 'nl', 'en', 'Netherlands');
INSERT INTO translations VALUES ('countries', 'iso', 'no', 'en', 'Norway');
INSERT INTO translations VALUES ('countries', 'iso', 'np', 'en', 'Nepal');
INSERT INTO translations VALUES ('countries', 'iso', 'nr', 'en', 'Nauru');
INSERT INTO translations VALUES ('countries', 'iso', 'nz', 'en', 'New Zealand');
INSERT INTO translations VALUES ('countries', 'iso', 'om', 'en', 'Oman');
INSERT INTO translations VALUES ('countries', 'iso', 'pa', 'en', 'Panama');
INSERT INTO translations VALUES ('countries', 'iso', 'pe', 'en', 'Peru');
INSERT INTO translations VALUES ('countries', 'iso', 'pg', 'en', 'Papua New Guinea');
INSERT INTO translations VALUES ('countries', 'iso', 'ph', 'en', 'Philippines');
INSERT INTO translations VALUES ('countries', 'iso', 'pk', 'en', 'Pakistan');
INSERT INTO translations VALUES ('countries', 'iso', 'pl', 'en', 'Poland');
INSERT INTO translations VALUES ('countries', 'iso', 'pr', 'en', 'Puerto Rico');
INSERT INTO translations VALUES ('countries', 'iso', 'pt', 'en', 'Portugal');
INSERT INTO translations VALUES ('countries', 'iso', 'pw', 'en', 'Palau');
INSERT INTO translations VALUES ('countries', 'iso', 'py', 'en', 'Paraguay');
INSERT INTO translations VALUES ('countries', 'iso', 'qa', 'en', 'Qatar');
INSERT INTO translations VALUES ('countries', 'iso', 'ro', 'en', 'Romania');
INSERT INTO translations VALUES ('countries', 'iso', 'ru', 'en', 'Russia');
INSERT INTO translations VALUES ('countries', 'iso', 'rw', 'en', 'Rwanda');
INSERT INTO translations VALUES ('countries', 'iso', 'sa', 'en', 'Saudi Arabia');
INSERT INTO translations VALUES ('countries', 'iso', 'sb', 'en', 'Solomon Islands');
INSERT INTO translations VALUES ('countries', 'iso', 'sc', 'en', 'Seychelles');
INSERT INTO translations VALUES ('countries', 'iso', 'sd', 'en', 'Sudan');
INSERT INTO translations VALUES ('countries', 'iso', 'se', 'en', 'Sweden');
INSERT INTO translations VALUES ('countries', 'iso', 'sg', 'en', 'Singapore');
INSERT INTO translations VALUES ('countries', 'iso', 'si', 'en', 'Slovenia');
INSERT INTO translations VALUES ('countries', 'iso', 'sk', 'en', 'Slovakia');
INSERT INTO translations VALUES ('countries', 'iso', 'sl', 'en', 'Sierra Leone');
INSERT INTO translations VALUES ('countries', 'iso', 'sm', 'en', 'San Marino');
INSERT INTO translations VALUES ('countries', 'iso', 'sn', 'en', 'Senegal');
INSERT INTO translations VALUES ('countries', 'iso', 'so', 'en', 'Somalia');
INSERT INTO translations VALUES ('countries', 'iso', 'sr', 'en', 'Suriname');
INSERT INTO translations VALUES ('countries', 'iso', 'st', 'en', 'Sao Tome and Principe');
INSERT INTO translations VALUES ('countries', 'iso', 'sv', 'en', 'El Salvador');
INSERT INTO translations VALUES ('countries', 'iso', 'sy', 'en', 'Syria');
INSERT INTO translations VALUES ('countries', 'iso', 'sz', 'en', 'Swaziland');
INSERT INTO translations VALUES ('countries', 'iso', 'tc', 'en', 'Turks and Caicos Islands');
INSERT INTO translations VALUES ('countries', 'iso', 'td', 'en', 'Chad');
INSERT INTO translations VALUES ('countries', 'iso', 'tg', 'en', 'Togo');
INSERT INTO translations VALUES ('countries', 'iso', 'th', 'en', 'Thailand');
INSERT INTO translations VALUES ('countries', 'iso', 'tj', 'en', 'Tajikistan');
INSERT INTO translations VALUES ('countries', 'iso', 'tm', 'en', 'Turkmenistan');
INSERT INTO translations VALUES ('countries', 'iso', 'tn', 'en', 'Tunisia');
INSERT INTO translations VALUES ('countries', 'iso', 'to', 'en', 'Tonga');
INSERT INTO translations VALUES ('countries', 'iso', 'tr', 'en', 'Turkey');
INSERT INTO translations VALUES ('countries', 'iso', 'tt', 'en', 'Trinidad and Tobago');
INSERT INTO translations VALUES ('countries', 'iso', 'tv', 'en', 'Tuvalu');
INSERT INTO translations VALUES ('countries', 'iso', 'tw', 'en', 'Taiwan');
INSERT INTO translations VALUES ('countries', 'iso', 'tz', 'en', 'Tanzania');
INSERT INTO translations VALUES ('countries', 'iso', 'ua', 'en', 'Ukraine');
INSERT INTO translations VALUES ('countries', 'iso', 'ug', 'en', 'Uganda');
INSERT INTO translations VALUES ('countries', 'iso', 'uk', 'en', 'United Kingdom');
INSERT INTO translations VALUES ('countries', 'iso', 'us', 'en', 'United States');
INSERT INTO translations VALUES ('countries', 'iso', 'uy', 'en', 'Uruguay');
INSERT INTO translations VALUES ('countries', 'iso', 'uz', 'en', 'Uzbekistan');
INSERT INTO translations VALUES ('countries', 'iso', 'va', 'en', 'Vatican');
INSERT INTO translations VALUES ('countries', 'iso', 'vc', 'en', 'Saint Vincent');
INSERT INTO translations VALUES ('countries', 'iso', 've', 'en', 'Venezuela');
INSERT INTO translations VALUES ('countries', 'iso', 'vn', 'en', 'Vietnam');
INSERT INTO translations VALUES ('countries', 'iso', 'vu', 'en', 'Vanuatu');
INSERT INTO translations VALUES ('countries', 'iso', 'ws', 'en', 'Samoa');
INSERT INTO translations VALUES ('countries', 'iso', 'ye', 'en', 'Yemen');
INSERT INTO translations VALUES ('countries', 'iso', 'yu', 'en', 'Yugoslavia');
INSERT INTO translations VALUES ('countries', 'iso', 'za', 'en', 'South Africa');
INSERT INTO translations VALUES ('countries', 'iso', 'zm', 'en', 'Zambia');
INSERT INTO translations VALUES ('countries', 'iso', 'zr', 'en', 'Zaire');
INSERT INTO translations VALUES ('countries', 'iso', 'zw', 'en', 'Zimbabue');

/** FRENCH */
/* civility */
INSERT INTO translations VALUES('users', 'civility', 1, 'fr', 'M.');
INSERT INTO translations VALUES('users', 'civility', 2, 'fr', 'Mme.');
INSERT INTO translations VALUES('users', 'civility', 3, 'fr', 'Mlle.');

/* hard coded rooms */
INSERT INTO translations VALUES ('rooms', 'name', 'out', 'fr', 'Extérieur' );
INSERT INTO translations VALUES ('rooms', 'name', 'venue', 'fr', 'Sur place' );

/* payment means */
INSERT INTO translations VALUES ('payment', 'name', 'CHQ',    'fr', 'Chèque' );
INSERT INTO translations VALUES ('payment', 'name', 'CASH',   'fr', 'Liquide' );
INSERT INTO translations VALUES ('payment', 'name', 'ONLINE', 'fr', 'En ligne' );

/* ISO-3166 country codes (http://www.ics.uci.edu/pub/websoft/wwwstat/country-codes.txt) */
INSERT INTO translations VALUES ('countries', 'iso', 'ad', 'fr', 'Andorre');
INSERT INTO translations VALUES ('countries', 'iso', 'ae', 'fr', 'Emirats Arabes Unis');
INSERT INTO translations VALUES ('countries', 'iso', 'af', 'fr', 'Afghanistan');
INSERT INTO translations VALUES ('countries', 'iso', 'ag', 'fr', 'Antigua et Barbuda');
INSERT INTO translations VALUES ('countries', 'iso', 'ai', 'fr', 'Anguilla');
INSERT INTO translations VALUES ('countries', 'iso', 'al', 'fr', 'Albanie');
INSERT INTO translations VALUES ('countries', 'iso', 'am', 'fr', 'Arménie');
INSERT INTO translations VALUES ('countries', 'iso', 'an', 'fr', 'Antilles Néerlandaises');
INSERT INTO translations VALUES ('countries', 'iso', 'ao', 'fr', 'Angola');
INSERT INTO translations VALUES ('countries', 'iso', 'ar', 'fr', 'Argentine');
INSERT INTO translations VALUES ('countries', 'iso', 'at', 'fr', 'Autriche');
INSERT INTO translations VALUES ('countries', 'iso', 'au', 'fr', 'Australie');
INSERT INTO translations VALUES ('countries', 'iso', 'aw', 'fr', 'Aruba');
INSERT INTO translations VALUES ('countries', 'iso', 'az', 'fr', 'Azerbaïdjan');
INSERT INTO translations VALUES ('countries', 'iso', 'ba', 'fr', 'Bosnie - Herzégovine');
INSERT INTO translations VALUES ('countries', 'iso', 'bb', 'fr', 'Barbade');
INSERT INTO translations VALUES ('countries', 'iso', 'bd', 'fr', 'Bengladesh');
INSERT INTO translations VALUES ('countries', 'iso', 'be', 'fr', 'Belgique');
INSERT INTO translations VALUES ('countries', 'iso', 'bf', 'fr', 'Burkina Faso');
INSERT INTO translations VALUES ('countries', 'iso', 'bg', 'fr', 'Bulgarie');
INSERT INTO translations VALUES ('countries', 'iso', 'bh', 'fr', 'Bahrein');
INSERT INTO translations VALUES ('countries', 'iso', 'bi', 'fr', 'Burundi');
INSERT INTO translations VALUES ('countries', 'iso', 'bj', 'fr', 'Bénin');
INSERT INTO translations VALUES ('countries', 'iso', 'bm', 'fr', 'Bermudes');
INSERT INTO translations VALUES ('countries', 'iso', 'bn', 'fr', 'Brunei Darussalam');
INSERT INTO translations VALUES ('countries', 'iso', 'bo', 'fr', 'Bolivie');
INSERT INTO translations VALUES ('countries', 'iso', 'br', 'fr', 'Brésil');
INSERT INTO translations VALUES ('countries', 'iso', 'bs', 'fr', 'Bahamas');
INSERT INTO translations VALUES ('countries', 'iso', 'bt', 'fr', 'Bhoutan');
INSERT INTO translations VALUES ('countries', 'iso', 'bw', 'fr', 'Botswana');
INSERT INTO translations VALUES ('countries', 'iso', 'by', 'fr', 'Belarus');
INSERT INTO translations VALUES ('countries', 'iso', 'bz', 'fr', 'Belize');
INSERT INTO translations VALUES ('countries', 'iso', 'ca', 'fr', 'Canada');
INSERT INTO translations VALUES ('countries', 'iso', 'cf', 'fr', 'République Centrafricaine');
INSERT INTO translations VALUES ('countries', 'iso', 'cg', 'fr', 'Congo');
INSERT INTO translations VALUES ('countries', 'iso', 'ch', 'fr', 'Suisse');
INSERT INTO translations VALUES ('countries', 'iso', 'ci', 'fr', 'Côte d\'Ivoire');
INSERT INTO translations VALUES ('countries', 'iso', 'cl', 'fr', 'Chili');
INSERT INTO translations VALUES ('countries', 'iso', 'cm', 'fr', 'Cameroun');
INSERT INTO translations VALUES ('countries', 'iso', 'cn', 'fr', 'Chine');
INSERT INTO translations VALUES ('countries', 'iso', 'co', 'fr', 'Colombie');
INSERT INTO translations VALUES ('countries', 'iso', 'cr', 'fr', 'Costa Rica');
INSERT INTO translations VALUES ('countries', 'iso', 'cu', 'fr', 'Cuba');
INSERT INTO translations VALUES ('countries', 'iso', 'cv', 'fr', 'Cap Vert');
INSERT INTO translations VALUES ('countries', 'iso', 'cx', 'fr', 'Ile Christmas');
INSERT INTO translations VALUES ('countries', 'iso', 'cy', 'fr', 'Chypre');
INSERT INTO translations VALUES ('countries', 'iso', 'cz', 'fr', 'République Tchèque');
INSERT INTO translations VALUES ('countries', 'iso', 'de', 'fr', 'Allemagne');
INSERT INTO translations VALUES ('countries', 'iso', 'dj', 'fr', 'Djibouti');
INSERT INTO translations VALUES ('countries', 'iso', 'dk', 'fr', 'Danemark');
INSERT INTO translations VALUES ('countries', 'iso', 'dm', 'fr', 'Dominique');
INSERT INTO translations VALUES ('countries', 'iso', 'do', 'fr', 'République Dominicaine');
INSERT INTO translations VALUES ('countries', 'iso', 'dz', 'fr', 'Algérie');
INSERT INTO translations VALUES ('countries', 'iso', 'ec', 'fr', 'Equateur');
INSERT INTO translations VALUES ('countries', 'iso', 'ee', 'fr', 'Estonie');
INSERT INTO translations VALUES ('countries', 'iso', 'eg', 'fr', 'Egypte');
INSERT INTO translations VALUES ('countries', 'iso', 'eh', 'fr', 'Sahara Occidental');
INSERT INTO translations VALUES ('countries', 'iso', 'er', 'fr', 'Erythrée');
INSERT INTO translations VALUES ('countries', 'iso', 'es', 'fr', 'Espagne');
INSERT INTO translations VALUES ('countries', 'iso', 'et', 'fr', 'Ethiopie');
INSERT INTO translations VALUES ('countries', 'iso', 'fi', 'fr', 'Finlande');
INSERT INTO translations VALUES ('countries', 'iso', 'fj', 'fr', 'Fidji');
INSERT INTO translations VALUES ('countries', 'iso', 'fr', 'fr', 'France');
INSERT INTO translations VALUES ('countries', 'iso', 'fr', 'en', 'France');
INSERT INTO translations VALUES ('countries', 'iso', 'ga', 'fr', 'Gabon');
INSERT INTO translations VALUES ('countries', 'iso', 'gd', 'fr', 'Grenade');
INSERT INTO translations VALUES ('countries', 'iso', 'ge', 'fr', 'Géorgie');
INSERT INTO translations VALUES ('countries', 'iso', 'gh', 'fr', 'Ghana');
INSERT INTO translations VALUES ('countries', 'iso', 'gi', 'fr', 'Gibraltar');
INSERT INTO translations VALUES ('countries', 'iso', 'gl', 'fr', 'Gambie');
INSERT INTO translations VALUES ('countries', 'iso', 'gn', 'fr', 'Guinée');
INSERT INTO translations VALUES ('countries', 'iso', 'gq', 'fr', 'Guinée Equatoriale');
INSERT INTO translations VALUES ('countries', 'iso', 'gr', 'fr', 'Grèce');
INSERT INTO translations VALUES ('countries', 'iso', 'gt', 'fr', 'Guatemala');
INSERT INTO translations VALUES ('countries', 'iso', 'gw', 'fr', 'Guinée-Bissau');
INSERT INTO translations VALUES ('countries', 'iso', 'gy', 'fr', 'Guyana');
INSERT INTO translations VALUES ('countries', 'iso', 'hk', 'fr', 'Hong Kong');
INSERT INTO translations VALUES ('countries', 'iso', 'hn', 'fr', 'Honduras');
INSERT INTO translations VALUES ('countries', 'iso', 'hr', 'fr', 'Croatie');
INSERT INTO translations VALUES ('countries', 'iso', 'ht', 'fr', 'Haïti');
INSERT INTO translations VALUES ('countries', 'iso', 'hu', 'fr', 'Hongrie');
INSERT INTO translations VALUES ('countries', 'iso', 'id', 'fr', 'Indonésie');
INSERT INTO translations VALUES ('countries', 'iso', 'ie', 'fr', 'Irlande');
INSERT INTO translations VALUES ('countries', 'iso', 'il', 'fr', 'Israël');
INSERT INTO translations VALUES ('countries', 'iso', 'in', 'fr', 'Inde');
INSERT INTO translations VALUES ('countries', 'iso', 'iq', 'fr', 'Irak');
INSERT INTO translations VALUES ('countries', 'iso', 'ir', 'fr', 'Iran');
INSERT INTO translations VALUES ('countries', 'iso', 'is', 'fr', 'Islande');
INSERT INTO translations VALUES ('countries', 'iso', 'it', 'fr', 'Italie');
INSERT INTO translations VALUES ('countries', 'iso', 'jm', 'fr', 'Jamaïque');
INSERT INTO translations VALUES ('countries', 'iso', 'jo', 'fr', 'Jordanie');
INSERT INTO translations VALUES ('countries', 'iso', 'jp', 'fr', 'Japon');
INSERT INTO translations VALUES ('countries', 'iso', 'ke', 'fr', 'Kenya');
INSERT INTO translations VALUES ('countries', 'iso', 'kg', 'fr', 'Kirgizstan');
INSERT INTO translations VALUES ('countries', 'iso', 'ki', 'fr', 'Kiribati');
INSERT INTO translations VALUES ('countries', 'iso', 'kh', 'fr', 'République Khmère');
INSERT INTO translations VALUES ('countries', 'iso', 'km', 'fr', 'Comores');
INSERT INTO translations VALUES ('countries', 'iso', 'kn', 'fr', 'Saint Kitts et Nevis');
INSERT INTO translations VALUES ('countries', 'iso', 'kp', 'fr', 'Corée du Nord');
INSERT INTO translations VALUES ('countries', 'iso', 'kr', 'fr', 'Corée du Sud');
INSERT INTO translations VALUES ('countries', 'iso', 'kw', 'fr', 'Kowait');
INSERT INTO translations VALUES ('countries', 'iso', 'ky', 'fr', 'Iles Cayman');
INSERT INTO translations VALUES ('countries', 'iso', 'kz', 'fr', 'Kazakhstan');
INSERT INTO translations VALUES ('countries', 'iso', 'la', 'fr', 'Laos');
INSERT INTO translations VALUES ('countries', 'iso', 'lb', 'fr', 'Liban');
INSERT INTO translations VALUES ('countries', 'iso', 'lc', 'fr', 'Sainte-Lucie');
INSERT INTO translations VALUES ('countries', 'iso', 'li', 'fr', 'Liechtenstein');
INSERT INTO translations VALUES ('countries', 'iso', 'lk', 'fr', 'Sri Lanka');
INSERT INTO translations VALUES ('countries', 'iso', 'lr', 'fr', 'Liberia');
INSERT INTO translations VALUES ('countries', 'iso', 'ls', 'fr', 'Lesotho');
INSERT INTO translations VALUES ('countries', 'iso', 'lt', 'fr', 'Lithuanie');
INSERT INTO translations VALUES ('countries', 'iso', 'lu', 'fr', 'Luxembourg');
INSERT INTO translations VALUES ('countries', 'iso', 'lv', 'fr', 'Lettonie');
INSERT INTO translations VALUES ('countries', 'iso', 'ly', 'fr', 'Libye');
INSERT INTO translations VALUES ('countries', 'iso', 'ma', 'fr', 'Maroc');
INSERT INTO translations VALUES ('countries', 'iso', 'mc', 'fr', 'Monaco');
INSERT INTO translations VALUES ('countries', 'iso', 'md', 'fr', 'Moldavie');
INSERT INTO translations VALUES ('countries', 'iso', 'mg', 'fr', 'Madagascar');
INSERT INTO translations VALUES ('countries', 'iso', 'mk', 'fr', 'Macédoine');
INSERT INTO translations VALUES ('countries', 'iso', 'mh', 'fr', 'Iles Marshall');
INSERT INTO translations VALUES ('countries', 'iso', 'ml', 'fr', 'Mali');
INSERT INTO translations VALUES ('countries', 'iso', 'mm', 'fr', 'Myanmar');
INSERT INTO translations VALUES ('countries', 'iso', 'mn', 'fr', 'Mongolie');
INSERT INTO translations VALUES ('countries', 'iso', 'mo', 'fr', 'Macao');
INSERT INTO translations VALUES ('countries', 'iso', 'mr', 'fr', 'Mauritanie');
INSERT INTO translations VALUES ('countries', 'iso', 'ms', 'fr', 'Montserrat');
INSERT INTO translations VALUES ('countries', 'iso', 'mt', 'fr', 'Malte');
INSERT INTO translations VALUES ('countries', 'iso', 'mu', 'fr', 'Maurice');
INSERT INTO translations VALUES ('countries', 'iso', 'mv', 'fr', 'Maldives');
INSERT INTO translations VALUES ('countries', 'iso', 'mw', 'fr', 'Malawi');
INSERT INTO translations VALUES ('countries', 'iso', 'mx', 'fr', 'Mexique');
INSERT INTO translations VALUES ('countries', 'iso', 'my', 'fr', 'Malaisie');
INSERT INTO translations VALUES ('countries', 'iso', 'mz', 'fr', 'Mozambique');
INSERT INTO translations VALUES ('countries', 'iso', 'na', 'fr', 'Namibie');
INSERT INTO translations VALUES ('countries', 'iso', 'ne', 'fr', 'Niger');
INSERT INTO translations VALUES ('countries', 'iso', 'ng', 'fr', 'Nigeria');
INSERT INTO translations VALUES ('countries', 'iso', 'ni', 'fr', 'Nicaragua');
INSERT INTO translations VALUES ('countries', 'iso', 'nl', 'fr', 'Pays-Bas');
INSERT INTO translations VALUES ('countries', 'iso', 'no', 'fr', 'Norvège');
INSERT INTO translations VALUES ('countries', 'iso', 'np', 'fr', 'Népal');
INSERT INTO translations VALUES ('countries', 'iso', 'nr', 'fr', 'Nauru');
INSERT INTO translations VALUES ('countries', 'iso', 'nz', 'fr', 'Nouvelle Zélande');
INSERT INTO translations VALUES ('countries', 'iso', 'om', 'fr', 'Oman');
INSERT INTO translations VALUES ('countries', 'iso', 'pa', 'fr', 'Panama');
INSERT INTO translations VALUES ('countries', 'iso', 'pe', 'fr', 'Pérou');
INSERT INTO translations VALUES ('countries', 'iso', 'pg', 'fr', 'Papouasie Nouvelle Guinée');
INSERT INTO translations VALUES ('countries', 'iso', 'ph', 'fr', 'Philippines');
INSERT INTO translations VALUES ('countries', 'iso', 'pk', 'fr', 'Pakistan');
INSERT INTO translations VALUES ('countries', 'iso', 'pl', 'fr', 'Pologne');
INSERT INTO translations VALUES ('countries', 'iso', 'pr', 'fr', 'Porto Rico');
INSERT INTO translations VALUES ('countries', 'iso', 'pt', 'fr', 'Portugal');
INSERT INTO translations VALUES ('countries', 'iso', 'pw', 'fr', 'Palau');
INSERT INTO translations VALUES ('countries', 'iso', 'py', 'fr', 'Paraguay');
INSERT INTO translations VALUES ('countries', 'iso', 'qa', 'fr', 'Qatar');
INSERT INTO translations VALUES ('countries', 'iso', 'ro', 'fr', 'Roumanie');
INSERT INTO translations VALUES ('countries', 'iso', 'ru', 'fr', 'Russie');
INSERT INTO translations VALUES ('countries', 'iso', 'rw', 'fr', 'Rwanda');
INSERT INTO translations VALUES ('countries', 'iso', 'sa', 'fr', 'Arabie Saoudite');
INSERT INTO translations VALUES ('countries', 'iso', 'sb', 'fr', 'Iles Salomon');
INSERT INTO translations VALUES ('countries', 'iso', 'sc', 'fr', 'Seychelles');
INSERT INTO translations VALUES ('countries', 'iso', 'sd', 'fr', 'Soudan');
INSERT INTO translations VALUES ('countries', 'iso', 'se', 'fr', 'Suède');
INSERT INTO translations VALUES ('countries', 'iso', 'sg', 'fr', 'Singapour');
INSERT INTO translations VALUES ('countries', 'iso', 'si', 'fr', 'Slovénie');
INSERT INTO translations VALUES ('countries', 'iso', 'sk', 'fr', 'République Slovaque');
INSERT INTO translations VALUES ('countries', 'iso', 'sl', 'fr', 'Sierra Leone');
INSERT INTO translations VALUES ('countries', 'iso', 'sm', 'fr', 'Saint Marin');
INSERT INTO translations VALUES ('countries', 'iso', 'sn', 'fr', 'Sénégal');
INSERT INTO translations VALUES ('countries', 'iso', 'so', 'fr', 'Somalie');
INSERT INTO translations VALUES ('countries', 'iso', 'sr', 'fr', 'Surinam');
INSERT INTO translations VALUES ('countries', 'iso', 'st', 'fr', 'Sao Tomé et Principe');
INSERT INTO translations VALUES ('countries', 'iso', 'sv', 'fr', 'El Salvador');
INSERT INTO translations VALUES ('countries', 'iso', 'sy', 'fr', 'Syrie');
INSERT INTO translations VALUES ('countries', 'iso', 'sz', 'fr', 'Swaziland');
INSERT INTO translations VALUES ('countries', 'iso', 'tc', 'fr', 'Iles Turks et Caicos');
INSERT INTO translations VALUES ('countries', 'iso', 'td', 'fr', 'Tchad');
INSERT INTO translations VALUES ('countries', 'iso', 'tg', 'fr', 'Togo');
INSERT INTO translations VALUES ('countries', 'iso', 'th', 'fr', 'Thaïlande');
INSERT INTO translations VALUES ('countries', 'iso', 'tj', 'fr', 'Tadjikistan');
INSERT INTO translations VALUES ('countries', 'iso', 'tm', 'fr', 'Turkménistan');
INSERT INTO translations VALUES ('countries', 'iso', 'tn', 'fr', 'Tunisie');
INSERT INTO translations VALUES ('countries', 'iso', 'to', 'fr', 'Tonga');
INSERT INTO translations VALUES ('countries', 'iso', 'tr', 'fr', 'Turquie');
INSERT INTO translations VALUES ('countries', 'iso', 'tt', 'fr', 'Trinidad et Tobago');
INSERT INTO translations VALUES ('countries', 'iso', 'tv', 'fr', 'Tuvalu');
INSERT INTO translations VALUES ('countries', 'iso', 'tw', 'fr', 'Taïwan');
INSERT INTO translations VALUES ('countries', 'iso', 'tz', 'fr', 'Tanzanie');
INSERT INTO translations VALUES ('countries', 'iso', 'ua', 'fr', 'Ukraine');
INSERT INTO translations VALUES ('countries', 'iso', 'ug', 'fr', 'Ouganda');
INSERT INTO translations VALUES ('countries', 'iso', 'uk', 'fr', 'Royaume Uni');
INSERT INTO translations VALUES ('countries', 'iso', 'us', 'fr', 'Etats-Unis');
INSERT INTO translations VALUES ('countries', 'iso', 'uy', 'fr', 'Uruguay');
INSERT INTO translations VALUES ('countries', 'iso', 'uz', 'fr', 'Ouzbékistan');
INSERT INTO translations VALUES ('countries', 'iso', 'va', 'fr', 'Vatican');
INSERT INTO translations VALUES ('countries', 'iso', 'vc', 'fr', 'Saint Vincent');
INSERT INTO translations VALUES ('countries', 'iso', 've', 'fr', 'Venezuela');
INSERT INTO translations VALUES ('countries', 'iso', 'vn', 'fr', 'Viet Nam');
INSERT INTO translations VALUES ('countries', 'iso', 'vu', 'fr', 'Vanuatu');
INSERT INTO translations VALUES ('countries', 'iso', 'ws', 'fr', 'Samoa');
INSERT INTO translations VALUES ('countries', 'iso', 'ye', 'fr', 'Yémen');
INSERT INTO translations VALUES ('countries', 'iso', 'yu', 'fr', 'Yougoslavie');
INSERT INTO translations VALUES ('countries', 'iso', 'za', 'fr', 'Afrique du Sud');
INSERT INTO translations VALUES ('countries', 'iso', 'zm', 'fr', 'Zambie');
INSERT INTO translations VALUES ('countries', 'iso', 'zr', 'fr', 'Zaïre');
INSERT INTO translations VALUES ('countries', 'iso', 'zw', 'fr', 'Zimbabwe');

/** PORTUGUESE */
/* civility */
INSERT INTO translations VALUES('users', 'civility', 1, 'pt', 'Sr.');
INSERT INTO translations VALUES('users', 'civility', 2, 'pt', 'Sra.');
INSERT INTO translations VALUES('users', 'civility', 3, 'pt', 'Sra.');

/* hard coded rooms */
INSERT INTO translations VALUES ('rooms', 'name', 'out', 'pt', 'Exterior' );
INSERT INTO translations VALUES ('rooms', 'name', 'venue', 'pt', 'Local da conferência' );

/* payment means */
INSERT INTO translations VALUES ('payment', 'name', 'CHQ',    'pt', 'Cheque' );
INSERT INTO translations VALUES ('payment', 'name', 'CASH',   'pt', 'Dinheiro' );
INSERT INTO translations VALUES ('payment', 'name', 'ONLINE', 'pt', 'Online' );

/* ISO-3166 country codes (http://www.ics.uci.edu/pub/websoft/wwwstat/country-codes.txt) */
