#!perl -w

use strict;
use Test::More tests => 109;

my @tests = (
{ profile => {
      required => [ qw(r1 r2) ],
      optional => [ qw(r3) ],
  },
  inputs => [
    { input  => { r1 => 1, r2 => 2 },
      fields => { r1 => 1, r2 => 2 },
      valid  => 1,
    },
    { input  => { r1 => 1, r2 => 2, r3 => 3 },
      fields => { r1 => 1, r2 => 2, r3 => 3 },
      valid  => 1,
    },
    { input  => { r1 => 1, r2 => 2, r3 => 3, r4 => 4 },
      fields => { r1 => 1, r2 => 2, r3 => 3 },
      valid  => 1,
    },
    { input  => { r1 => 'foo  ', r2 => '  bar', r3 => ' baz '},
      fields => { r1 => 'foo',   r2 => 'bar',   r3 => 'baz' },
      valid  => 1,
    },
    { input  => { r1 => 1, r3 => 3 },
      fields => { r1 => 1, r3 => 3 },
      valid  => '',
      invalid => { r2 => 'required' },
    },
    { input  => { r1 => 1, r2 => '', r3 => 3 },
      fields => { r1 => 1, r3 => 3 },
      valid  => '',
      invalid => { r2 => 'required' },
    },
  ],
},
{ profile => {
      dependencies => { r1 => [ qw(r2 r3) ] },
  },
  inputs => [
    { input  => {  },
      fields => {  },
      valid  => 1,
    },
    { input  => { r1 => 1, r2 => 2, r3 => 3 },
      fields => { r1 => 1, r2 => 2, r3 => 3 },
      valid  => 1,
    },
    { input  => { r1 => 1 },
      fields => { r1 => 1 },
      valid  => '',
      invalid => { r2 => 'required', r3 => 'required' },
    },
    { input  => { r1 => 1, r2 => 2 },
      fields => { r1 => 1, r2 => 2 },
      invalid => { r3 => 'required' },
      valid  => '',
    },
  ],
},
{ profile => {
      dependencies => { r1 => [ qw(r2) ],
                        r3 => [ qw(r4) ],
                      },
  },
  inputs => [
    { input  => { r1 => 1 },
      fields => { r1 => 1 },
      valid  => '',
      invalid => { r2 => 'required' },
    },
    { input  => { r1 => 1, r2 => 2 },
      fields => { r1 => 1, r2 => 2 },
      valid  => 1,
    },
    { input  => { r1 => 1, r2 => 2, r3 => 3 },
      fields => { r1 => 1, r2 => 2, r3 => 3 },
      valid  => '',
      invalid => { r4 => 'required' },
    },
    { input  => { r1 => 1, r3 => 3 },
      fields => { r1 => 1, r3 => 3 },
      valid  => '',
      invalid => { r2 => 'required', r4 => 'required' },
    },
    { input  => { r1 => 1, r2 => 2, r3 => 3, r4 => 4 },
      fields => { r1 => 1, r2 => 2, r3 => 3, r4 => 4 },
      valid  => 1,
    },
  ],
},
{ profile => {
      required => 'r1',
      constraints => { r1 => 'email' },
  },
  inputs => [
    { input  => { r1 => 'foo@example.com' },
      fields => { r1 => 'foo@example.com' },
      valid  => 1,
    },
    { input  => { r1 => 'foo@example' },
      fields => { r1 => 'foo@example' },
      valid  => '',
      invalid => { r1 => 'email' },
    },
    { input  => {  },
      fields => {  },
      valid  => '',
      invalid => { r1 => 'required' },
    },
  ],
},
{ profile => {
      required => 'r1',
      constraints => { r1 => 'numeric' },
  },
  inputs => [
    { input  => { r1 => 42 },
      fields => { r1 => 42 },
      valid  => 1,
    },
    { input  => { r1 => 0 },
      fields => { r1 => 0 },
      valid  => 1,
    },
    { input  => {  },
      fields => {  },
      valid  => '',
      invalid => { r1 => 'required' },
    },
    { input  => { r1 => 'abc' },
      fields => { r1 => 'abc' },
      valid  => '',
      invalid => { r1 => 'numeric' },
    },
  ],
},
{ profile => {
      optional    => 'r1',
      constraints => { r1 => 'numeric' },
  },
  inputs => [
    { input  => { r1 => 42 },
      fields => { r1 => 42 },
      valid  => 1,
    },
    { input  => { r1 => undef },
      fields => {  },
      valid  => 1,
    },
    { input  => { r1 => '' },
      fields => { },
      valid  => 1,
    },
    { input  => { r1 => 'abc' },
      fields => { r1 => 'abc' },
      valid  => '',
      invalid => { r1 => 'numeric' },
    },
  ],
},
{ profile => {
      optional    => 'r1',
      constraints => { r1 => sub { $_[0] =~ /^[A-Z]*$/ } },
  },
  inputs => [
    { input  => { r1 => 'ABC' },
      fields => { r1 => 'ABC' },
      valid  => 1,
    },
    { input  => {  },
      fields => {  },
      valid  => 1,
    },
    { input  => { r1 => 'abc' },
      fields => { r1 => 'abc' },
      valid  => '',
      invalid => { r1 => 'custom' },
    },
  ],
},
{ profile => {
      required    => 'r1',
      constraints => { r1 => 'url' },
  },
  inputs => [
    { input  => { r1 => 42 },
      fields => { r1 => 42 },
      valid  => '',
      invalid => { r1 => 'url' },
    },
    { input  => { r1 => 'http://abc' },
      fields => { r1 => 'http://abc' },
      valid  => 1,
    },
  ],
},
{ profile => {
      required    => 'r1',
      optional    => 'r2',
      filters     => {
         r1 => sub { lc shift },
         r2 => sub { ucfirst lc shift },
      },
  },
  inputs => [
    { input  => { r1 => 'FOO' },
      fields => { r1 => 'foo' },
      valid  => 1,
    },
    { input  => { r1 => 'FOO', r2 => 'bAr' },
      fields => { r1 => 'foo', r2 => 'Bar' },
      valid  => 1,
    },
  ],
},
);
require_ok('Act::Form');

for my $t (@tests) {
    my $f = Act::Form->new(%{$t->{profile}});
    ok($f);
    for my $i (@{$t->{inputs}}) {
        my $res = $f->validate($i->{input});
        is($res, $i->{valid});
        is_deeply($f->fields, $i->{fields});
        if ($i->{invalid}) {
            is_deeply($f->invalid, $i->{invalid});
        }
        else {
            ok(!defined($i->{invalid}));
        }
    }
}

__END__
