package Act::Country;
use strict;

# iso => ISO-3166 (http://www.ics.uci.edu/pub/websoft/wwwstat/country-codes.txt)
our @Countries = (
   { iso => 'ad', fr => 'Andorre',                   en => 'Andorra',                    },
   { iso => 'ae', fr => 'Emirats Arabes Unis',       en => 'United Arab Emirates',       },
   { iso => 'af', fr => 'Afghanistan',               en => 'Afghanistan',                },
   { iso => 'ag', fr => 'Antigua et Barbuda',        en => 'Antigua and Barbuda',        },
   { iso => 'ai', fr => 'Anguilla',                  en => 'Anguilla',                   },
   { iso => 'al', fr => 'Albanie',                   en => 'Albania',                    },
   { iso => 'am', fr => 'Arménie',                   en => 'Armenia',                    },
   { iso => 'an', fr => 'Antilles Néerlandaises',    en => 'Netherlands Antilles',       },
   { iso => 'ao', fr => 'Angola',                    en => 'Angola',                     },
   { iso => 'ar', fr => 'Argentine',                 en => 'Argentina',                  },
   { iso => 'at', fr => 'Autriche',                  en => 'Austria',                    },
   { iso => 'au', fr => 'Australie',                 en => 'Australia',                  },
   { iso => 'aw', fr => 'Aruba',                     en => 'Aruba',                      },
   { iso => 'az', fr => 'Azerbaïdjan',               en => 'Azerbaijan',                 },
   { iso => 'ba', fr => 'Bosnie - Herzégovine',      en => 'Bosnia and Herzegovina',     },
   { iso => 'bb', fr => 'Barbade',                   en => 'Barbados',                   },
   { iso => 'bd', fr => 'Bengladesh',                en => 'Bangladesh',                 },
   { iso => 'be', fr => 'Belgique',                  en => 'Belgium',                    },
   { iso => 'bf', fr => 'Burkina Faso',              en => 'Burkina Faso',               },
   { iso => 'bg', fr => 'Bulgarie',                  en => 'Bulgaria',                   },
   { iso => 'bh', fr => 'Bahrein',                   en => 'Bahrain',                    },
   { iso => 'bi', fr => 'Burundi',                   en => 'Burundi',                    },
   { iso => 'bj', fr => 'Bénin',                     en => 'Benin',                      },
   { iso => 'bm', fr => 'Bermudes',                  en => 'Bermuda',                    },
   { iso => 'bn', fr => 'Brunei Darussalam',         en => 'Brunei Darussalam',          },
   { iso => 'bo', fr => 'Bolivie',                   en => 'Bolivia',                    },
   { iso => 'br', fr => 'Brésil',                    en => 'Brazil',                     },
   { iso => 'bs', fr => 'Bahamas',                   en => 'Bahamas',                    },
   { iso => 'bt', fr => 'Bhoutan',                   en => 'Bhutan',                     },
   { iso => 'bw', fr => 'Botswana',                  en => 'Botswana',                   },
   { iso => 'by', fr => 'Belarus',                   en => 'Belarus',                    },
   { iso => 'bz', fr => 'Belize',                    en => 'Belize',                     },
   { iso => 'ca', fr => 'Canada',                    en => 'Canada',                     },
   { iso => 'cf', fr => 'République Centrafricaine', en => 'Central African Republic',   },
   { iso => 'cg', fr => 'Congo',                     en => 'Congo',                      },
   { iso => 'ch', fr => 'Suisse',                    en => 'Switzerland',                },
   { iso => 'ci', fr => "Côte d'Ivoire",             en => "Côte d'Ivoire",              },
   { iso => 'cl', fr => 'Chili',                     en => 'Chile',                      },
   { iso => 'cm', fr => 'Cameroun',                  en => 'Cameroon',                   },
   { iso => 'cn', fr => 'Chine',                     en => 'China',                      },
   { iso => 'co', fr => 'Colombie',                  en => 'Colombia',                   },
   { iso => 'cr', fr => 'Costa Rica',                en => 'Costa Rica',                 },
   { iso => 'cu', fr => 'Cuba',                      en => 'Cuba',                       },
   { iso => 'cv', fr => 'Cap Vert',                  en => 'Cape Verde',                 },
   { iso => 'cx', fr => 'Ile Christmas',             en => 'Christmas Island',           },
   { iso => 'cy', fr => 'Chypre',                    en => 'Cyprus',                     },
   { iso => 'cz', fr => 'République Tchèque',        en => 'Czech Republic',             },
   { iso => 'de', fr => 'Allemagne',                 en => 'Germany',                    },
   { iso => 'dj', fr => 'Djibouti',                  en => 'Djibouti',                   },
   { iso => 'dk', fr => 'Danemark',                  en => 'Denmark',                    },
   { iso => 'dm', fr => 'Dominique',                 en => 'Dominica',                   },
   { iso => 'do', fr => 'République Dominicaine',    en => 'Dominican Republic',         },
   { iso => 'dz', fr => 'Algérie',                   en => 'Algeria',                    },
   { iso => 'ec', fr => 'Equateur',                  en => 'Ecuador',                    },
   { iso => 'ee', fr => 'Estonie',                   en => 'Estonia',                    },
   { iso => 'eg', fr => 'Egypte',                    en => 'Egypt',                      },
   { iso => 'eh', fr => 'Sahara Occidental',         en => 'Western Sahara',             },
   { iso => 'er', fr => 'Erythrée',                  en => 'Eritrea',                    },
   { iso => 'es', fr => 'Espagne',                   en => 'Spain',                      },
   { iso => 'et', fr => 'Ethiopie',                  en => 'Ethiopia',                   },
   { iso => 'fi', fr => 'Finlande',                  en => 'Finland',                    },
   { iso => 'fj', fr => 'Fidji',                     en => 'Fiji',                       },
   { iso => 'fr', fr => 'France',                    en => 'France',                     },
   { iso => 'ga', fr => 'Gabon',                     en => 'Gabon',                      },
   { iso => 'gd', fr => 'Grenade',                   en => 'Grenada',                    },
   { iso => 'ge', fr => 'Géorgie',                   en => 'Georgia',                    },
   { iso => 'gh', fr => 'Ghana',                     en => 'Ghana',                      },
   { iso => 'gi', fr => 'Gibraltar',                 en => 'Gibraltar',                  },
   { iso => 'gl', fr => 'Gambie',                    en => 'Gambia',                     },
   { iso => 'gn', fr => 'Guinée',                    en => 'Guinea',                     },
   { iso => 'gq', fr => 'Guinée Equatoriale',        en => 'Equatorial Guinea',          },
   { iso => 'gr', fr => 'Grèce',                     en => 'Greece',                     },
   { iso => 'gt', fr => 'Guatemala',                 en => 'Guatemala',                  },
   { iso => 'gw', fr => 'Guinée-Bissau',             en => 'Guinea-Bissau',              },
   { iso => 'gy', fr => 'Guyana',                    en => 'Guyana',                     },
   { iso => 'hk', fr => 'Hong Kong',                 en => 'Hong Kong',                  },
   { iso => 'hn', fr => 'Honduras',                  en => 'Honduras',                   },
   { iso => 'hr', fr => 'Croatie',                   en => 'Croatia',                    },
   { iso => 'ht', fr => 'Haïti',                     en => 'Haiti',                      },
   { iso => 'hu', fr => 'Hongrie',                   en => 'Hungary',                    },
   { iso => 'id', fr => 'Indonésie',                 en => 'Indonesia',                  },
   { iso => 'ie', fr => 'Irlande',                   en => 'Ireland',                    },
   { iso => 'il', fr => 'Israël',                    en => 'Israel',                     },
   { iso => 'in', fr => 'Inde',                      en => 'India',                      },
   { iso => 'iq', fr => 'Irak',                      en => 'Iraq',                       },
   { iso => 'ir', fr => 'Iran',                      en => 'Iran',                       },
   { iso => 'is', fr => 'Islande',                   en => 'Iceland',                    },
   { iso => 'it', fr => 'Italie',                    en => 'Italy',                      },
   { iso => 'jm', fr => 'Jamaïque',                  en => 'Jamaica',                    },
   { iso => 'jo', fr => 'Jordanie',                  en => 'Jordan',                     },
   { iso => 'jp', fr => 'Japon',                     en => 'Japan',                      },
   { iso => 'ke', fr => 'Kenya',                     en => 'Kenya',                      },
   { iso => 'kg', fr => 'Kirgizstan',                en => 'Kyrgyzstan',                 },
   { iso => 'ki', fr => 'Kiribati',                  en => 'Kiribati',                   },
   { iso => 'kh', fr => 'République Khmère',         en => 'Cambodia',                   },
   { iso => 'km', fr => 'Comores',                   en => 'Comoros',                    },
   { iso => 'kn', fr => 'Saint Kitts et Nevis',      en => 'Saint Kitts and Nevis',      },
   { iso => 'kp', fr => 'Corée du Nord',             en => 'Korea, North',               },
   { iso => 'kr', fr => 'Corée du Sud',              en => 'Korea, South',               },
   { iso => 'kw', fr => 'Kowait',                    en => 'Kuwait',                     },
   { iso => 'ky', fr => 'Iles Cayman',               en => 'Cayman Islands',             },
   { iso => 'kz', fr => 'Kazakhstan',                en => 'Kazakhstan',                 },
   { iso => 'la', fr => 'Laos',                      en => 'Laos',                       },
   { iso => 'lb', fr => 'Liban',                     en => 'Lebanon',                    },
   { iso => 'lc', fr => 'Sainte-Lucie',              en => 'Saint Lucia',                },
   { iso => 'li', fr => 'Liechtenstein',             en => 'Liechtenstein',              },
   { iso => 'lk', fr => 'Sri Lanka',                 en => 'Sri Lanka',                  },
   { iso => 'lr', fr => 'Liberia',                   en => 'Liberia',                    },
   { iso => 'ls', fr => 'Lesotho',                   en => 'Lesotho',                    },
   { iso => 'lt', fr => 'Lithuanie',                 en => 'Lithuania',                  },
   { iso => 'lu', fr => 'Luxembourg',                en => 'Luxembourg',                 },
   { iso => 'lv', fr => 'Lettonie',                  en => 'Latvia',                     },
   { iso => 'ly', fr => 'Libye',                     en => 'Libya',                      },
   { iso => 'ma', fr => 'Maroc',                     en => 'Morocco',                    },
   { iso => 'mc', fr => 'Monaco',                    en => 'Monaco',                     },
   { iso => 'md', fr => 'Moldavie',                  en => 'Moldova',                    },
   { iso => 'mg', fr => 'Madagascar',                en => 'Madagascar',                 },
   { iso => 'mk', fr => 'Macédoine',                 en => 'Macedonia',                  },
   { iso => 'mh', fr => 'Iles Marshall',             en => 'Marshall Islands',           },
   { iso => 'ml', fr => 'Mali',                      en => 'Mali',                       },
   { iso => 'mm', fr => 'Myanmar',                   en => 'Myanmar',                    },
   { iso => 'mn', fr => 'Mongolie',                  en => 'Mongolia',                   },
   { iso => 'mo', fr => 'Macao',                     en => 'Macao',                      },
   { iso => 'mr', fr => 'Mauritanie',                en => 'Mauritania',                 },
   { iso => 'ms', fr => 'Montserrat',                en => 'Montserrat',                 },
   { iso => 'mt', fr => 'Malte',                     en => 'Malta',                      },
   { iso => 'mu', fr => 'Maurice',                   en => 'Mauritius',                  },
   { iso => 'mv', fr => 'Maldives',                  en => 'Maldives',                   },
   { iso => 'mw', fr => 'Malawi',                    en => 'Malawi',                     },
   { iso => 'mx', fr => 'Mexique',                   en => 'Mexico',                     },
   { iso => 'my', fr => 'Malaisie',                  en => 'Malaysia',                   },
   { iso => 'mz', fr => 'Mozambique',                en => 'Mozambique',                 },
   { iso => 'na', fr => 'Namibie',                   en => 'Namibia',                    },
   { iso => 'ne', fr => 'Niger',                     en => 'Niger',                      },
   { iso => 'ng', fr => 'Nigeria',                   en => 'Nigeria',                    },
   { iso => 'ni', fr => 'Nicaragua',                 en => 'Nicaragua',                  },
   { iso => 'nl', fr => 'Pays-Bas',                  en => 'Netherlands',                },
   { iso => 'no', fr => 'Norvège',                   en => 'Norway',                     },
   { iso => 'np', fr => 'Népal',                     en => 'Nepal',                      },
   { iso => 'nr', fr => 'Nauru',                     en => 'Nauru',                      },
   { iso => 'nz', fr => 'Nouvelle Zélande',          en => 'New Zealand',                },
   { iso => 'om', fr => 'Oman',                      en => 'Oman',                       },
   { iso => 'pa', fr => 'Panama',                    en => 'Panama',                     },
   { iso => 'pe', fr => 'Pérou',                     en => 'Peru',                       },
   { iso => 'pg', fr => 'Papouasie Nouvelle Guinée', en => 'Papua New Guinea',           },
   { iso => 'ph', fr => 'Philippines',               en => 'Philippines',                },
   { iso => 'pk', fr => 'Pakistan',                  en => 'Pakistan',                   },
   { iso => 'pl', fr => 'Pologne',                   en => 'Poland',                     },
   { iso => 'pr', fr => 'Porto Rico',                en => 'Puerto Rico',                },
   { iso => 'pt', fr => 'Portugal',                  en => 'Portugal',                   },
   { iso => 'pw', fr => 'Palau',                     en => 'Palau',                      },
   { iso => 'py', fr => 'Paraguay',                  en => 'Paraguay',                   },
   { iso => 'qa', fr => 'Qatar',                     en => 'Qatar',                      },
   { iso => 'ro', fr => 'Roumanie',                  en => 'Romania',                    },
   { iso => 'ru', fr => 'Russie',                    en => 'Russia',                     },
   { iso => 'rw', fr => 'Rwanda',                    en => 'Rwanda',                     },
   { iso => 'sa', fr => 'Arabie Saoudite',           en => 'Saudi Arabia',               },
   { iso => 'sb', fr => 'Iles Salomon',              en => 'Solomon Islands',            },
   { iso => 'sc', fr => 'Seychelles',                en => 'Seychelles',                 },
   { iso => 'sd', fr => 'Soudan',                    en => 'Sudan',                      },
   { iso => 'se', fr => 'Suède',                     en => 'Sweden',                     },
   { iso => 'sg', fr => 'Singapour',                 en => 'Singapore',                  },
   { iso => 'si', fr => 'Slovénie',                  en => 'Slovenia',                   },
   { iso => 'sk', fr => 'République Slovaque',       en => 'Slovakia',                   },
   { iso => 'sl', fr => 'Sierra Leone',              en => 'Sierra Leone',               },
   { iso => 'sm', fr => 'Saint Marin',               en => 'San Marino',                 },
   { iso => 'sn', fr => 'Sénégal',                   en => 'Senegal',                    },
   { iso => 'so', fr => 'Somalie',                   en => 'Somalia',                    },
   { iso => 'sr', fr => 'Surinam',                   en => 'Suriname',                   },
   { iso => 'st', fr => 'Sao Tomé et Principe',      en => 'Sao Tome and Principe',      },
   { iso => 'sv', fr => 'El Salvador',               en => 'El Salvador',                },
   { iso => 'sy', fr => 'Syrie',                     en => 'Syria',                      },
   { iso => 'sz', fr => 'Swaziland',                 en => 'Swaziland',                  },
   { iso => 'tc', fr => 'Iles Turks et Caicos',      en => 'Turks and Caicos Islands',   },
   { iso => 'td', fr => 'Tchad',                     en => 'Chad',                       },
   { iso => 'tg', fr => 'Togo',                      en => 'Togo',                       },
   { iso => 'th', fr => 'Thaïlande',                 en => 'Thailand',                   },
   { iso => 'tj', fr => 'Tadjikistan',               en => 'Tajikistan',                 },
   { iso => 'tm', fr => 'Turkménistan',              en => 'Turkmenistan',               },
   { iso => 'tn', fr => 'Tunisie',                   en => 'Tunisia',                    },
   { iso => 'to', fr => 'Tonga',                     en => 'Tonga',                      },
   { iso => 'tr', fr => 'Turquie',                   en => 'Turkey',                     },
   { iso => 'tt', fr => 'Trinidad et Tobago',        en => 'Trinidad and Tobago',        },
   { iso => 'tv', fr => 'Tuvalu',                    en => 'Tuvalu',                     },
   { iso => 'tw', fr => 'Taïwan',                    en => 'Taiwan',                     },
   { iso => 'tz', fr => 'Tanzanie',                  en => 'Tanzania',                   },
   { iso => 'ua', fr => 'Ukraine',                   en => 'Ukraine',                    },
   { iso => 'ug', fr => 'Ouganda',                   en => 'Uganda',                     },
   { iso => 'uk', fr => 'Royaume Uni',               en => 'United Kingdom',             },
   { iso => 'us', fr => 'Etats-Unis',                en => 'United States',              },
   { iso => 'uy', fr => 'Uruguay',                   en => 'Uruguay',                    },
   { iso => 'uz', fr => 'Ouzbékistan',               en => 'Uzbekistan',                 },
   { iso => 'va', fr => 'Vatican',                   en => 'Vatican',                    },
   { iso => 'vc', fr => 'Saint Vincent',             en => 'Saint Vincent',              },
   { iso => 've', fr => 'Venezuela',                 en => 'Venezuela',                  },
   { iso => 'vn', fr => 'Viet Nam',                  en => 'Vietnam',                    },
   { iso => 'vu', fr => 'Vanuatu',                   en => 'Vanuatu',                    },
   { iso => 'ws', fr => 'Samoa',                     en => 'Samoa',                      },
   { iso => 'ye', fr => 'Yémen',                     en => 'Yemen',                      },
   { iso => 'yu', fr => 'Yougoslavie',               en => 'Yugoslavia',                 },
   { iso => 'za', fr => 'Afrique du Sud',            en => 'South Africa',               },
   { iso => 'zm', fr => 'Zambie',                    en => 'Zambia',                     },
   { iso => 'zr', fr => 'Zaïre',                     en => 'Zaire',                      },
   { iso => 'zw', fr => 'Zimbabwe',                  en => 'Zimbabue',                   },
);

our %Countries_by_iso = map { $_->{iso} => $_ } @Countries;

sub CountryNames
{
   my ($lang) = @_;
   return
     [
      sort { $a->{name} cmp $b->{name} }
      map {{ iso => $_->{iso}, name => $_->{$lang} }}
      @Countries
     ];
}

sub CountryName
{
   my ($code, $lang) = @_;
   return $Countries_by_iso{$code}{$lang} || $code;
}

1;

__END__
