=head1 User guide and reference manual for Act

An overview of Act's features is available in L<Act::Manual::Features>.

The Act user manual is divided in several subsections, aimed at
the different kind of users of the Act conference toolkit:

=over 4

=item L<Act::Manual::Organizer>

This section contains information for conference organiser hosted on
a web server using Act.

=item L<Act::Manual::Provider>

This section contains setup details and performance tricks for
application providers: people that host an Act instance on their system.

=item L<Act::Manual::Developer>

This section contains detailed explanations on the inner workings
of the Act toolkit and how to add components to it.

=item L<Act::Manual::Credits>

Author and contributor credits, with a bit of project history.

=back

=cut

