=head1 The Act configuration file

Most of the configuration items for your conference are stored in the
file F<act.ini>. It is divided in several sections, some of which
are related to the Act infrastructure itself, and others to your own
conference.

=head1 SECTIONS

=head2 Conference configuration

    [general]
    # this conference's full production URI
    # with trailing slash
    full_uri = http://conferences.mongueurs.net/foo2004/
    
    # supported languages, and the default language
    languages   = fr en                
    default_language = fr
    
    # name of the conference in each supported language
    name_en = The foo2004 conference
    name_fr = L'atelier Perl foo2004
    
    # default country and timezone for new users
    default_country  = fr
    timezone  = Europe/Paris
    
    [registration]
    open = 1
    # optional maximum number of attendees
    # omit this is not applicable
    max_attendees = 100

    [email]
    sender_address = your@address.com
    
    [talks]
    # conference dates
    start_date = 2004-06-05 18:00:00
    end_date   = 2004-06-07 18:00:00
    
    # default talk durations
    durations = 20 40 120
    
    # can talks be submitted?
    submissions_open = 0
    
    # submission notification emails settings
    submissions_notify_address  = interventions@mongueurs.net
    submissions_notify_language = fr
    
    # email the speaker when the talk is accepted
    notify_accept = 1
    
    # can users edit talks?
    edition_open  = 1
    
    # is the schedule publically visible?
    show_schedule = 1
    
    # show accepted talks, or all
    show_all  = 0
    
    # talk languages. Use only for
    # multilingual conferences.
    languages = en fr
    
    # target audience. Omit this, and
    # the [levels] section, if not used
    levels = 4
    
    [levels]
    # level names in all supported languages
    level1_name_en = Any
    level2_name_en = Beginner
    level3_name_en = Intermediate
    level4_name_en = Advanced
    
    [rooms]
    # list of rooms (must match /r\d+/)
    rooms = r1 r2
    
    # room names in all supported languages
    r1_name_en = LMET
    r2_name_en = O'Reilly
    
    [payment]
    open        = 0
    
    # which online payment system? (Fake/NONE/YEF/TPF/...)
    #  Fake: payment simulation, for tests
    #  NONE: the conference is free
    #  YEF:  using the YAPC Europe Foundation's payment system
    #  TPF:  using The Perl Foundation's payment system
    #  PaypalFoo: using a Paypal account
    type        = YEF
    
    # if type is "NONE", the following configuration should be ommitted
    
    # currency. Valid values depends on the payment type
    currency    = EUR
    
    # how many different registration prices
    prices      = 2        
    
    # Details on each price. name_ can be provided
    # in each supported language, or at least in
    # the default language
    [price1]
    name_en     = Regular price
    name_fr     = Tarif normal
    amount      = 25
    
    [price2]
    name_en     = Reduced price
    amount      = 15

=head2 Infrastructure configuration

Conference organisers can skip this section.

    [database]
    name        = act
    dsn         = dbi:Pg:dbname=$(database_name)
    user        = foo
    passwd      = sekr3t
    pg_dump     = /home/pgsql/bin/pg_dump     # dumping tool
    dump_file   = /home/act/actdb             # where to dump the db
    dump_needs_password = 1
    
    [general]
    conferences = fpw2004 fpw2005            # conferences handled by Act
    cookie_name = act
    dir_photos  = photos                     # where photos are stored
    
    [email]
    smtp_server = localhost
    smtp_port   = 0
    test        = 0

=cut
