=head1 The Act configuration file

Most of the configuration items for your conference are stored in the
file F<act.ini>.

    [general]
    # this conference's full production URI
    # with trailing slash
    full_uri = http://conferences.mongueurs.net/foo2004/
    
    # supported languages, and the default language
    #    You can specify a language variant, e.g. en_US or en_GB.
    #    If you do, specify it solely in the "languages" entry,
    #    use the main language ("en") everywhere else.
    languages   = fr en_US
    default_language = en
    
    # name of the conference in each supported language
    name_en = The foo2004 conference
    name_fr = L'atelier Perl foo2004
    
    # default country and timezone for new users
    default_country  = fr
    timezone  = Europe/Paris
    
    # pager limit for the user search page
    searchlimit = 25
    
    [registration]
    open = 1
    # optional maximum number of attendees
    # omit this is not applicable
    max_attendees = 100

    # optional
    # selects different phrases about "buying tickets", to be used when
    # people can get it without actually paying. NOTE: if you set this to
    # 1, there really should be a registration price of 0, otherwise users
    # will get the nasty surprise of having to pay for a ticket that was
    # promised "free of charge"...
    gratis = 1

    [email]
    sender_address = your@address.com
    
    [talks]
    # conference dates
    start_date = 2004-06-05 18:00:00
    end_date   = 2004-06-07 18:00:00
    
    # default talk durations
    durations = 20 40 120
    
    # can talks be submitted?
    submissions_open = 0
    
    # submission notification emails settings
    submissions_notify_address  = interventions@mongueurs.net
    submissions_notify_language = fr
    
    # email the speaker when the talk is accepted
    notify_accept = 1
    
    # can users edit talks?
    edition_open  = 1
    
    # is the schedule publically visible?
    show_schedule = 1

    # schedule date to show when none specified
    schedule_default = 2004-06-06
    
    # show accepted talks, or all
    show_all  = 0
    
    # talk languages. Use only for
    # multilingual conferences.
    languages = en fr
    
    # target audience. Omit this, and
    # the [levels] section, if not used
    levels = 4
    
    [levels]
    # level names in all supported languages
    level1_name_en = Any
    level2_name_en = Beginner
    level3_name_en = Intermediate
    level4_name_en = Advanced
    
    [rooms]
    # list of rooms (must match /r\d+/)
    rooms = r1 r2
    
    # room names in all supported languages
    r1_name_en = LMET
    r2_name_en = O'Reilly
    
    [payment]
    open        = 0
    
    # which online payment system? (Fake/NONE/YEF/TPF/...)
    #  Fake: payment simulation, for tests
    #  NONE: the conference is free
    #  YEF:  using the YAPC Europe Foundation's payment system
    #  TPF:  using The Perl Foundation's payment system
    #  PaypalFoo: using a Paypal account
    type        = YEF
    
    # if type is "NONE", the following configuration should be ommitted
    
    # currency. Valid values depends on the payment type
    currency    = EUR
    
    # the products your are selling
    # these are non user visible product codes for configuration purposes only
    # "registration" is special - it's the registration product
    products    = registration accomodation
    
    # Details on each product
    [product_registration]
    name_en     = Registration
    name_fr     = Inscription
    prices      = 3
    
    [product_registration_price1]
    name_en     = Early bird
    name_fr     = Tarif réduit
    amount      = 15

    [product_registration_price2]
    name_en     = Normal price
    name_fr     = Tarif normal
    amount      = 20

    [product_registration_price3]
    name_en     = Student price
    name_fr     = Tarif étudiant
    amount      = 10
    # users must enter promotion code to select this price
    promocode   = qwerty
    
    # configure any additional products
    [product_accomodation]
    name_en     = Accomodation
    name_fr     = Hébergement
    prices      = 1
    
    # you can omit price name if there's only one price
    [product_accomodation_price1]
    amount      = 15
  

=cut
