=head1 Developer documentation for Act

This section of the manual is aimed at Act developers and contributors.

It is divided in several subsections, each detailing a different
area of the Act internals:

=over 4

=item L<Act::Manual::Developer::Resources>

A list of resources available to developers.

=item L<Act::Manual::Developer::Installation>

Installing Act.

=item L<Act::Manual::Developer::Translation>

How to write a new language translation for Act.

=item L<Act::Manual::Developer::Unicode>

Some information about Unicode in Act.

=item L<Act::Manual::Developer::Templates>

Using Act templates.

=item L<Act::Manual::Developer::Config>

Global configuration variables used in Act.

=item L<Act::Manual::Developer::Handlers>

How to write handlers.

=item L<Act::Manual::Developer::Database>

Act's database usage.

=back

=cut

