=head1 User guide for Act conference organizers

This section of the manual is aimed at conference organizers,
that is, the "users" of Act from the point of view of the developers.

It is divided in several subsections, each detailing a different
area of using Act for a conference:

=over 4

=item L<Act::Manual::Organizer::Layout>

This section describe the layout of a single conference repository:
where to put the templates, how to write them, 

=item L<Act::Manual::Organizer::Configuration>

A detailed description of the content of the F<act.ini> configuration file.

=item L<Act::Manual::Organizer::Schedule>

Some tips on how to organize the conference schedule using the tools
in Act.

=item L<Act::Manual::Organizer::News>

How to create, publish and display news items.

=item L<Act::Manual::Organizer::Templates>

The list of all templates that an organizer I<might> want to override
for a conference.

=item L<Act::Manual::Organizer::Payment>

Information on Act's online payment feature and configuration.

=item L<Act::Manual::Organizer::Photos>

How to create photo galleries.

=back

=cut

